/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berichtserstellungssystem;

import java.sql.*;




/**
 *
 * @author Baraa
 */
public class Berichtserstellungssystem {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws SQLException {
        // TODO code application logic here
        Connect myConnector = new Connect();
        Connection myConnection = myConnector.connect();
        
        /*try {
            System.out.println("Connecting database...");
            Class.forName("org.hsqldb.jdbcDriver");
            String url = "jdbc:hsqldb:file:C:\\Users\\Baraa\\Desktop\\INF202\\Berichtserstellungssystem\\database\\";
            Connection con = DriverManager.getConnection(url, "INF202", "inf2020");
            System.out.println("Database connected!");
            Statement stmt = con.createStatement();

            ResultSet rs;
            int result;
            result = stmt.executeUpdate("CREATE TABLE tutorials_tb4 (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1) PRIMARY KEY," +
            "title VARCHAR(50) NOT NULL," +
            "author VARCHAR(20) NOT NULL," +
            "submission_date DATE)");

            result = stmt.executeUpdate("INSERT INTO tutorials_tb4 (title, author, submission_date) " +
            "VALUES ('Learn PHP', 'John Poul', NOW())");
            con.commit();
            rs = stmt.executeQuery("SELECT * FROM tutorials_tb4");
            while (rs.next()) {
            System.out.println(rs.getString("Title"));
             }

            result = stmt.executeUpdate("UPDATE tutorials_tb4 SET title = 'C and Data Structures' WHERE id = 0;");
            con.commit();
            } catch (ClassNotFoundException e) {
            System.out.println("Database connection error. ClassNotFoundException: " + e);
            } catch (SQLException e) {
            System.out.println("Database connection error. SQLException: " + e);
            }*/
    }
    
}
